create table SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36),
    ATTRIBUTE_NAME     VARCHAR(200),
    ATTRIBUTE_BYTES    LONGVARBINARY,
    SESSIONPRIMARYID   INTEGER not null,
    ATTRIBUTEBYTES     BINARY(255),
    ATTRIBUTENAME      VARCHAR(255)
);

