create table PRODUCT_CHECK_OUT_TEXT
(
    ID              INT not null,
    PRODUCT_NAME_DE MEDIUMTEXT,
    PRODUCT_NAME_EN MEDIUMTEXT,
    PRODUCT_NAME_ES MEDIUMTEXT,
    PRODUCT_NAME_FR MEDIUMTEXT,
    PRODUCT_NAME_IT MEDIUMTEXT,
    PRODUCT_NAME_TR MEDIUMTEXT,
    ARTIKELNUMMER   LONG,
    ID_PRODUCTS     INT,
    constraint " PRODUCT_CHECK_OUT_TEXT_PK"
        primary key (ID)
);

